dist: xenial
language: python
sudo: false

addons:
   apt:
     update: true


matrix:
  include:

    - name: "pip 3.6"
      python: 3.6
      env: DISTRIB="pip"

    - name: "conda 3.7"
      python: 3.7
      env: DISTRIB="conda"
      after_success: coveralls || echo "coveralls failed"

    - name: "conda 3.8"
      python: 3.8
      env: DISTRIB="conda"

    - name: "pip 3.8"
      python: 3.8
      env: DISTRIB="pip"

install:
  - if [[ "${DISTRIB}" == "conda" ]];
    then
      py_major=${TRAVIS_PYTHON_VERSION:0:1};
      wget https://repo.continuum.io/miniconda/Miniconda${py_major}-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      source "$HOME/miniconda/etc/profile.d/conda.sh";
      conda config --set always_yes yes;
      conda update conda;
      conda env create -f requirements/environment.yml;
      conda activate elephant;
      pip list;
    else
      pip install -r requirements/requirements.txt;
    fi

  - pip -V
  - pip install coverage coveralls nose
  - python setup.py install
  - pip list
  - python --version

script:
  nosetests --with-coverage --cover-package=viziphant
